/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type ScriptInputsStruct = {
  pub_a_x: BytesLike;
  pub_a_y: BytesLike;
  pub_c_x: BytesLike;
  pub_c_y: BytesLike;
  cipher: BytesLike;
};

export type ScriptInputsStructOutput = [
  pub_a_x: string,
  pub_a_y: string,
  pub_c_x: string,
  pub_c_y: string,
  cipher: string
] & {
  pub_a_x: string;
  pub_a_y: string;
  pub_c_x: string;
  pub_c_y: string;
  cipher: string;
};

export interface BitMixInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "nonces"
      | "orderMap"
      | "validate"
      | "verifier"
      | "wbtcToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Deposit" | "OrderValidated"): EventFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "orderMap", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "validate",
    values: [BytesLike, BytesLike, BytesLike, [BigNumberish]]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(functionFragment: "wbtcToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orderMap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "validate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wbtcToken", data: BytesLike): Result;
}

export namespace DepositEvent {
  export type InputTuple = [
    user: AddressLike,
    orderID: BytesLike,
    nonce: BigNumberish,
    amount: BigNumberish,
    timeLock: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    orderID: string,
    nonce: bigint,
    amount: bigint,
    timeLock: bigint
  ];
  export interface OutputObject {
    user: string;
    orderID: string;
    nonce: bigint;
    amount: bigint;
    timeLock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderValidatedEvent {
  export type InputTuple = [orderID: BytesLike];
  export type OutputTuple = [orderID: string];
  export interface OutputObject {
    orderID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BitMix extends BaseContract {
  connect(runner?: ContractRunner | null): BitMix;
  waitForDeployment(): Promise<this>;

  interface: BitMixInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<
    [
      amount: BigNumberish,
      timeLock: BigNumberish,
      pubkey_x: BytesLike,
      pubkey_y: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  orderMap: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        ScriptInputsStructOutput,
        boolean
      ] & {
        amount: bigint;
        timeLock: bigint;
        nonce: bigint;
        depositedAt: bigint;
        pubkey_x: string;
        pubkey_y: string;
        scriptInputs: ScriptInputsStructOutput;
        isValidated: boolean;
      }
    ],
    "view"
  >;

  validate: TypedContractMethod<
    [
      orderID: BytesLike,
      _publicValues: BytesLike,
      _proofBytes: BytesLike,
      blockNumbers: [BigNumberish]
    ],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  wbtcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      timeLock: BigNumberish,
      pubkey_x: BytesLike,
      pubkey_y: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "orderMap"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        ScriptInputsStructOutput,
        boolean
      ] & {
        amount: bigint;
        timeLock: bigint;
        nonce: bigint;
        depositedAt: bigint;
        pubkey_x: string;
        pubkey_y: string;
        scriptInputs: ScriptInputsStructOutput;
        isValidated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "validate"
  ): TypedContractMethod<
    [
      orderID: BytesLike,
      _publicValues: BytesLike,
      _proofBytes: BytesLike,
      blockNumbers: [BigNumberish]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wbtcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "OrderValidated"
  ): TypedContractEvent<
    OrderValidatedEvent.InputTuple,
    OrderValidatedEvent.OutputTuple,
    OrderValidatedEvent.OutputObject
  >;

  filters: {
    "Deposit(address,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "OrderValidated(bytes32)": TypedContractEvent<
      OrderValidatedEvent.InputTuple,
      OrderValidatedEvent.OutputTuple,
      OrderValidatedEvent.OutputObject
    >;
    OrderValidated: TypedContractEvent<
      OrderValidatedEvent.InputTuple,
      OrderValidatedEvent.OutputTuple,
      OrderValidatedEvent.OutputObject
    >;
  };
}
