/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iLightclientSol from "./ILightclient.sol";
export { IProverContract__factory } from "./IProverContract__factory";
