/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lightclientSol from "./lightclient.sol";
export type { lightclientSol };
import type * as proverSol from "./prover.sol";
export type { proverSol };
import type * as wbtcSol from "./wbtc.sol";
export type { wbtcSol };
