/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iLightclientSol from "./ILightclient.sol";
export type { iLightclientSol };
export type { IProverContract } from "./IProverContract";
