/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBitcoinLightClient,
  IBitcoinLightClientInterface,
} from "../../../contracts/interfaces/IBitcoinLightClient";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "blockHashes",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBitcoinLightClient__factory {
  static readonly abi = _abi;
  static createInterface(): IBitcoinLightClientInterface {
    return new Interface(_abi) as IBitcoinLightClientInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBitcoinLightClient {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBitcoinLightClient;
  }
}
