/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as lightclientSol from "./lightclient.sol";
export * as proverSol from "./prover.sol";
export * as wbtcSol from "./wbtc.sol";
